import type { PolicyEdition } from '../policyContent'

export default {
  title: 'Privacy Policy',
  lastUpdated: 'August 26, 2026',
  effectiveDate: 'June 2, 2026',
  callout: [
    'Dutiva Canada Inc. ("Dutiva," "we," "us," or "our") provides HR compliance software for Canadian employers, HR professionals, and business operators. This Privacy Policy explains how we collect, use, disclose, retain, and protect personal information when you use Dutiva, including our website, application, Advisor, document workflows, beta access, support, and related services.',
    'This Policy is designed to support compliance with the Personal Information Protection and Electronic Documents Act (PIPEDA) and applicable provincial privacy laws, including Quebec privacy requirements where they apply. It does not replace any separate Data Processing Agreement, subscription agreement, or organization-specific privacy obligations that may apply to your use of Dutiva.',
  ],
  sections: [
    {
      title: '1. Who We Are',
      blocks: [
        {
          type: 'p',
          text: 'Dutiva Canada Inc. provides HR compliance software built for Canadian employers and HR teams. For account, website, billing, support, and product-usage information that we collect directly from users, Dutiva is responsible for that personal information under applicable Canadian privacy law.',
        },
        {
          type: 'p',
          text: 'Where an employer, HR professional, or organization enters personal information about employees, candidates, contractors, or other individuals into Dutiva, that organization is generally responsible for ensuring it has the authority, consent, notice, and internal policies required to use Dutiva for that information. Dutiva processes that information to provide the service, subject to this Policy and any applicable agreement with the customer.',
        },
        {
          type: 'p',
          text: 'Privacy questions, access requests, correction requests, and deletion requests can be sent to our Privacy Officer at privacy@dutiva.ca.',
        },
      ],
    },
    {
      title: '2. Information We Collect',
      blocks: [
        {
          type: 'p',
          text: 'Depending on how you use Dutiva, we may collect the following categories of personal information:',
        },
        {
          type: 'li',
          text: 'Account information: name, work email, authentication details, organization name, province or territory, role, plan, account status, and related account settings.',
        },
        {
          type: 'li',
          text: 'Workspace information: onboarding answers, employer profile details, selected province, territory, or applicable federal regime, organization size, preferred language, workflow preferences, saved settings, and in-app configuration choices.',
        },
        {
          type: 'li',
          text: 'Document information: document titles, template selections, jurisdiction or coverage-context codes, document inputs, saved drafts, generated documents, lifecycle status, export records, and electronic-signature workflow records.',
        },
        {
          type: 'li',
          text: 'Advisor messages: messages you submit to Dutiva Advisor, limited conversation history needed to provide the response, selected province, territory, or applicable federal regime, retrieved guidance context, and limited workspace context needed to make the response useful.',
        },
        {
          type: 'li',
          text: 'Usage, device, and security data: log data, IP address, browser and device information, pages or features used, timestamps, rate-limit signals, error logs, authentication events, and security events generated by our infrastructure.',
        },
        {
          type: 'li',
          text: 'Billing data: subscription status, invoice, payment, tax, and billing portal information processed through Stripe. Dutiva does not store full card numbers or banking credentials.',
        },
        {
          type: 'li',
          text: 'Beta, support, and communications data: beta waitlist submissions, feedback consent, support messages, survey responses, transactional email records, and communication preferences.',
        },
      ],
    },
    {
      title: '3. How We Use Information',
      blocks: [
        {
          type: 'p',
          text: 'We use personal information only for purposes needed to operate, secure, support, and improve Dutiva, including to:',
        },
        {
          type: 'li',
          text: 'provide, authenticate, operate, maintain, and secure the Dutiva service;',
        },
        {
          type: 'li',
          text: 'create accounts, manage access, apply plan limits, and support organization-level administration;',
        },
        {
          type: 'li',
          text: 'generate, save, review, export, and administer HR documents and electronic-signature workflows;',
        },
        {
          type: 'li',
          text: 'deliver Advisor responses, retrieve relevant guidance context, and improve the reliability and safety of HR compliance workflows;',
        },
        {
          type: 'li',
          text: 'process subscriptions, invoices, receipts, account notices, support requests, and service updates;',
        },
        {
          type: 'li',
          text: 'measure aggregate feature usage, troubleshoot errors, prevent abuse, enforce rate limits, and monitor service performance;',
        },
        {
          type: 'li',
          text: 'protect the security, availability, integrity, and lawful operation of Dutiva; and',
        },
        {
          type: 'li',
          text: 'comply with legal, tax, accounting, security, regulatory, dispute-resolution, and audit obligations.',
        },
        {
          type: 'p',
          text: 'We do not sell personal information. We do not use customer HR documents or Advisor messages for third-party advertising.',
        },
      ],
    },
    {
      title: '4. Service Providers and Disclosure',
      blocks: [
        {
          type: 'p',
          text: 'We disclose personal information only as needed to operate the service, comply with law, complete business transactions, or protect rights, safety, and security. Current core service providers may include:',
        },
        {
          type: 'li',
          text: 'Supabase: database, authentication, storage and edge functions, and edge functions.',
        },
        {
          type: 'li',
          text: 'Vercel: hosting, serverless functions, deployment, and operational logs.',
        },
        {
          type: 'li',
          text: 'DigitalOcean Gradient AI: model inference for Advisor responses, where message content and limited context are sent only as needed to produce the response.',
        },
        {
          type: 'li',
          text: 'Stripe: payments, subscriptions, invoices, tax, and billing portal operations.',
        },
        {
          type: 'li',
          text: 'Cloudflare: DNS, network security, performance, and availability services.',
        },
        {
          type: 'li',
          text: 'Google Analytics, if enabled: product or website analytics. The current application only loads this service when a measurement ID is configured and the user has granted consent through the consent banner.',
        },
        {
          type: 'li',
          text: 'TrustedSite (Halo Security): public-website security-scan trustmark. The marketing site loads their script so visitors can see scan status. It may receive the visitor\'s IP address and browser or device signals. It is not loaded in the signed-in workspace and is not used for advertising.',
        },
        {
          type: 'li',
          text: 'First-party support analytics: Help Centre searches, article views, helpfulness votes, and support ticket submission and status events. These events are optional and off by default — nothing is collected until the visitor accepts analytics through the consent banner. They are sent to a Dutiva-operated edge function in Canada and do not use third-party cookies. Anonymous Help Centre events carry a daily-rotated visitor identifier, not a user or workspace identifier. Authenticated ticket events carry the workspace (organization) identifier, not the individual user identifier. Raw event data is retained for 90 days; daily aggregates are retained indefinitely. See the Data Retention Policy for details.',
        },
        {
          type: 'p',
          text: 'We may also disclose information where required by law, court order, regulator request, legal process, merger or financing diligence, corporate transaction, or where reasonably necessary to protect the security and integrity of Dutiva, our users, or the public.',
        },
      ],
    },
    {
      title: '5. Consent and Choices',
      blocks: [
        {
          type: 'p',
          text: 'We rely on consent, contract necessity, legitimate service operations, and legal obligations as appropriate under Canadian privacy law. We identify purposes before or at collection unless the purpose is obvious from context or permitted by law.',
        },
        {
          type: 'p',
          text: 'You may withdraw optional consent, such as beta feedback communications or optional marketing communications, by using unsubscribe or preference controls where available, or by contacting us. Some information is required to provide the service, maintain security, complete billing, preserve audit records, or meet legal obligations.',
        },
      ],
    },
    {
      title: '6. Cross-Border Processing',
      blocks: [
        {
          type: 'p',
          text: 'Some service providers may process or store information outside Canada, including in the United States. When information is processed outside your province or outside Canada, it may be subject to the laws of that jurisdiction.',
        },
        {
          type: 'p',
          text: 'We use contractual, technical, and organizational safeguards designed to protect personal information during cross-border processing. For Quebec personal information, transfers outside Quebec are reviewed through a privacy impact assessment process before the transfer is approved, where required by applicable law.',
        },
      ],
    },
    {
      title: '7. AI Advisor Notice',
      blocks: [
        {
          type: 'p',
          text: 'Dutiva Advisor is an AI-powered workflow guidance feature. Advisor messages are sent to our server-side Advisor endpoint and then, where needed, to a third-party AI model provider for inference. We do not include payment details in AI requests, and we limit workspace context to the fields needed to make the response useful.',
        },
        {
          type: 'li',
          text: 'Do not submit social insurance numbers, medical records, banking credentials, personal health information, or highly sensitive employee records to the Advisor unless Dutiva expressly provides a controlled workflow for that type of information.',
        },
        {
          type: 'li',
          text: 'Advisor responses are generated by AI and are not reviewed by a lawyer before delivery.',
        },
        {
          type: 'li',
          text: 'Advisor responses provide general HR workflow support and compliance-oriented guidance. They are not legal advice and should not be treated as a substitute for professional review.',
        },
        {
          type: 'li',
          text: 'Dutiva does not make employment decisions for you. Employers, HR professionals, and authorized users remain responsible for reviewing outputs and making workplace decisions.',
        },
        {
          type: 'p',
          text: 'More detail is available in our AI Usage Disclosure and Legal Disclaimer.',
        },
      ],
    },
    {
      title: '8. Automated Decision-Making',
      blocks: [
        {
          type: 'p',
          text: 'Dutiva may use automated systems to generate drafts, retrieve guidance context, suggest next steps, enforce rate limits, monitor security, and support product functionality. Dutiva is designed to assist employer and HR workflows; it is not designed to make final hiring, discipline, accommodation, termination, compensation, or other employment decisions on behalf of customers.',
        },
        {
          type: 'p',
          text: 'Where automated processing produces a recommendation, draft, or guidance output, users should review the output before relying on it. If you have questions about automated processing associated with your personal information, contact us at privacy@dutiva.ca.',
        },
      ],
    },
    {
      title: '9. Retention and Deletion',
      blocks: [
        {
          type: 'p',
          text: 'We retain personal information only as long as needed for the purposes described in this Policy, unless a longer period is required or permitted for legal, tax, accounting, security, dispute, regulatory, or audit reasons.',
        },
        {
          type: 'li',
          text: 'Account and workspace data are retained while the account is active.',
        },
        {
          type: 'li',
          text: 'Saved documents remain available until deleted, archived, or the account is deleted, subject to legal retention requirements and customer configuration.',
        },
        {
          type: 'li',
          text: 'Self-initiated account deletion removes owned account rows and generated documents, then records an anonymized deletion audit entry.',
        },
        {
          type: 'li',
          text: 'Billing, tax, security, and audit records may be retained for required statutory or operational periods.',
        },
        {
          type: 'p',
          text: 'More detail is available in our Data Retention and Deletion Policy.',
        },
      ],
    },
    {
      title: '10. Your Privacy Rights',
      blocks: [
        {
          type: 'p',
          text: 'Subject to legal limits, you may request access to personal information we hold about you, correction of inaccurate information, withdrawal of consent, account deletion, and information about our privacy practices.',
        },
        {
          type: 'p',
          text: 'Quebec residents may also have rights to portability, de-indexing or erasure in certain circumstances, and information about automated decision-making that produces legal or similarly significant effects.',
        },
        {
          type: 'p',
          text: "You may also contact the Office of the Privacy Commissioner of Canada at priv.gc.ca or the Commission d'accès à l'information du Québec at cai.gouv.qc.ca.",
        },
      ],
    },
    {
      title: '11. Cookies, Local Storage, and Analytics',
      blocks: [
        {
          type: 'p',
          text: 'Dutiva uses strictly necessary authentication storage and local browser storage for settings such as language, theme, onboarding progress, and in-browser workflow state. Optional analytics are only loaded when configured in the application environment.',
        },
        {
          type: 'p',
          text: 'We do not use third-party advertising cookies or cross-site advertising trackers. More detail is available in our Cookie Policy.',
        },
      ],
    },
    {
      title: '12. Security and Breach Response',
      blocks: [
        {
          type: 'p',
          text: 'We use safeguards appropriate to the sensitivity of the information, including TLS in transit, access controls, authentication, service-role separation, rate limiting, audit-oriented deletion records, and operational monitoring.',
        },
        {
          type: 'p',
          text: 'If a privacy breach creates a real risk of significant harm, we will notify affected individuals and report to the Office of the Privacy Commissioner of Canada as soon as feasible, and we will keep required breach records. Quebec confidentiality incidents are handled under Quebec notification and recordkeeping requirements where applicable.',
        },
      ],
    },
    {
      title: '13. Updates to This Policy',
      blocks: [
        {
          type: 'p',
          text: 'We may update this Policy from time to time to reflect changes in our service, providers, legal obligations, or privacy practices. If we make material changes, we will provide notice in a manner appropriate to the change, such as by updating the date above, posting a notice in the service, or sending an account notice where appropriate.',
        },
      ],
    },
    {
      title: '14. Contact',
      blocks: [
        {
          type: 'p',
          text: 'Dutiva Canada Inc. – Privacy Officer',
        },
        {
          type: 'p',
          text: 'Email: privacy@dutiva.ca',
        },
        {
          type: 'p',
          text: 'Website: dutiva.ca',
        },
        {
          type: 'p',
          text: 'We aim to respond to privacy requests within 30 days where required by law, unless an extension is permitted or required.',
        },
      ],
    },
  ],
} satisfies PolicyEdition
